#include "nsISupports.idl"
[scriptable, uuid(eaa022aa-5cdf-43bb-97d3-37e06a1c7026)]
interface nsIRoadNetworkModel : nsISupports
{
    void run_step(in long milliseconds);
	string get_current_state();
};
