#include "nsISupports.idl"
[scriptable, uuid(4c490951-fc68-4780-8102-4f42e4bf422f)]
interface nsIRNModelParams : nsISupports
{
    // Interval in seconds between creation of new car.
    attribute float carGenerationInterval;
    // Distance in meters that is considered safe.
    attribute float safeDistance;

    attribute float maxSpeed;
    attribute float minSpeed;
};